In [1]:
import numpy as np

# Step 2: Create a 1D NumPy array with 12 random numbers between 1 and 100
arr_1d = np.random.randint(1, 101, 12)
print("1D Array:\n", arr_1d)

# Step 3: Reshape into 2D array (4x3 matrix)
arr_2d = arr_1d.reshape(4, 3)
print("\n2D Array (4x3):\n", arr_2d)

# Step 4a: Extract the second row
second_row = arr_2d[1]
print("\nSecond Row:\n", second_row)

# Step 4b: Extract the first column
first_col = arr_2d[:, 0]
print("\nFirst Column:\n", first_col)

# Step 4c: Extract the last two elements from the last row
last_two = arr_2d[-1, -2:]
print("\nLast two elements from the last row:\n", last_two)

# Step 5: Print shape, size, and data type
print("\nArray Shape:", arr_2d.shape)
print("Array Size:", arr_2d.size)
print("Array Data Type:", arr_2d.dtype)

1D Array:
 [74 29 19 72  5 92 80 53 45 84 35  1]

2D Array (4x3):
 [[74 29 19]
 [72  5 92]
 [80 53 45]
 [84 35  1]]

Second Row:
 [72  5 92]

First Column:
 [74 72 80 84]

Last two elements from the last row:
 [35  1]

Array Shape: (4, 3)
Array Size: 12
Array Data Type: int32
